### ISSUE TITLE
Sketch Practice homework

### ISSUE THREAD

**Issue by nevanscott** [nevanscott/uxui0818#23]
Homework needs to be finalized: https://github.com/nevanscott/uxui0818/blob/master/_homework/interaction-design/sketch-practice.md

I think this is the one that's like Desktop screens to practice with?

**Comment by nevanscott** [comment]
@lrbloomfield Sorry for pinging you with this so late at night, but if I'm not mistaken, this homework is for tomorrow night, right?

**Comment by lrbloomfield** [comment]
Yes @nevanscott, the pull request has been created. I put @elise2106 and @dzc1 as reviewers.

**Comment by nevanscott** [comment]
Thank you!!

Cheers,
Nevan
